### ISSUE TITLE
rdoclient is not able to pase response to JSON inside the library. 

### ISSUE THREAD

**Issue by walteree1** [RandomOrg/JSON-RPC-Python#8]
I am using this line:

```
from rdoclient import RandomOrgClient
random_org = RandomOrgClient(MY_TOKEN) 
response = random_org.generate_signed_integers(5, 0, 10, replacement=False, user_data={"data":"foo"})
```
NOTE: I was working a couple of days ago without any issue. Then, I got this. 

NOW, I'm getting this error. 
```
Exception in thread Thread-2 (_threaded_request_sending):
Traceback (most recent call last):
  File "C:\Users\Walte\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\Walte\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Walte\AppData\Local\Programs\Python\Python310\lib\site-packages\rdoclient\rdoclient.py", line 2717, in _threaded_request_sending
    data = self._send_request_core(request['request'])
  File "C:\Users\Walte\AppData\Local\Programs\Python\Python310\lib\site-packages\rdoclient\rdoclient.py", line 2768, in _send_request_core
    data=json.dumps(request),
  File "C:\Users\Walte\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\Walte\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Walte\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Walte\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type RandomOrgClient is not JSON serializable
```

PYTHON VERSION: 3.10.1

**Comment by RandomOrgDev** [comment]
Good afternoon,

Thank you for contacting us about this issue and apologies for only getting back to you now! I attempted to recreate the problem but did not get an error using the above code and Python v3.10.1. Are you still getting this error? 

If so, would you perhaps be able to provide further information? Which version of the rdoclient library and its dependencies (requests and six) are you using? Do you get the same error using other methods? Are you able to get results using the same API key in the [request builder](https://api.random.org/json-rpc/4/request-builder) on the website?

Many thanks in advance!

**Comment by walteree1** [comment]
Hello, I appreciate the response, regarding versions:

rdoclient==1.4.2
requests==2.27.1
six==1.16.0

And yes, using postman I get this response: 
**Request**:
host: https://api.random.org/json-rpc/4/invoke
headers: Content-Type:application/json
body:
```
{
    "jsonrpc": "2.0",
    "method": "generateSignedIntegers",
    "params": {
        "apiKey": "<hidden>",
        "n": 3,
        "min": 1,
        "max": 6,
        "replacement": true,
        "base": 10
    },
    "id": 6995
}
```

**Response**: 200
```
{
    "jsonrpc": "2.0",
    "result": {
        "random": {
            "method": "generateSignedIntegers",
            "hashedApiKey": "<hidden>",
            "n": 3,
            "min": 1,
            "max": 6,
            "replacement": true,
            "base": 10,
            "pregeneratedRandomization": null,
            "data": [
                4,
                4,
                2
            ],
            "license": {
                "type": "developer",
                "text": "Random values licensed strictly for development and testing only",
                "infoUrl": null
            },
            "licenseData": null,
            "userData": null,
            "ticketData": null,
            "completionTime": "2022-03-25 03:59:17Z",
            "serialNumber": 11
        },
        "signature": "V3aSmHKrrQal+VCRr2K8Dz9EML+ltQccYfA1OcyUosgiAuut0SlzI2K6owGO/HKkxPQ8lXOp1BJyfERrKnQMJny4jZhcubQsfWed3sG4NXJc+vWWnjJMNuFSNLNLm2znJpJ7rdIRy1yN8+1sLrGZ0JuyzDWAa+RH7O1ZFKIj53/kQQRZoLml97ys/2xbD8surnL6T1YFY16+pwKs0D/Uistujm1WyAjnNrwTC7DRbSoN8uvERgEoqFk6G3qknySln9Y3vzxX8C51j/El8Utt2TRuvK2sCkuz+yAsvq1E5aSyX+YpScbgLQQDAcKc8zVKic4u8Ig0FFE0A6AJgE3PqUSIXCNa2QD35dSZVyY0qcNRcK5y4jot1Y7rQU+kMCVp1FJ53604VZ3fe0qHj/VgD/cV/+yls/1qh+wq8e7W4yLxeY5MfgLsa1S3K0+JZl6jbKBG5Xsn1d6dzIXWw5kh9oJ3H2ECD5cOrtrvDIpaJe7wzu1oE7ihDjfNiBY7mrcwleEcqhprozx92uKy7/b0Xh/oWolaqzx8aZ7EKNPU4hctXKwfdjG3A0Df5fQGIbu0WBKr70lgijWD3SVcx2JyrM1oMiEQZ4+mbzdcEbxZZt+/bF6hHDMHMmTA2u7BUpvyU4rw+8+uZ1rSCpB6QIcjPa+Tw6bGRK2zRxQfqkD1jk4=",
        "cost": 0,
        "bitsUsed": 8,
        "bitsLeft": 249992,
        "requestsLeft": 999,
        "advisoryDelay": 1120
    },
    "id": 6995
}
```

**Comment by walteree1** [comment]
I uninstall python and reinstall everything again. It is working now. Thanks and the time. It looked like a corrupted package.
